### ISSUE TITLE
Search Bar / Nav Bar Layout Issues

### ISSUE THREAD

**Issue by SpeakkVisually** [LLK/scratch-www#101]
Certain languages cause strange, not user friendly, navigation bar layouts. 

In Polski (cut off Help buttton): 
![image](https://cloud.githubusercontent.com/assets/5166432/10645143/302b7166-77fa-11e5-9124-b92652298165.png)

In German (tiny Search bar):
![image](https://cloud.githubusercontent.com/assets/5166432/10645164/476399f8-77fa-11e5-9f17-e3ce78cb0c84.png)

**Comment by kaschm** [comment]
@carljbowman - maybe one for the design meeting? this needs discussion :)

**Comment by TheGrits** [comment]
@kaschm @carljbowman 
Looks like it has been fixed with the new nav bar: 
(responsive screen in Chrome Inspect Element, 907x1322)
![scratch mit edu-privacy_policy- 1](https://cloud.githubusercontent.com/assets/12952370/20035138/5530faea-a3ae-11e6-8f99-b138e75e9411.png)

(responsive screen in Chrome Inspect Element, 1144x1322)
![scratch mit edu-privacy_policy-](https://cloud.githubusercontent.com/assets/12952370/20035149/93d7951a-a3ae-11e6-9248-c5688fd86f52.png)

**Comment by kaschm** [comment]
good point, @TheGrits . 

@carljbowman - looks like the responsive nav takes care of the search bar situation. I still see some oddness with the nav bar on tablet / mobile sizes (see below - in german, the 'Login' gets cut off as I resize the browser window), but is that a separate issue? 

![screen shot 2016-11-07 at 10 14 16 am](https://cloud.githubusercontent.com/assets/782228/20062797/05b6b164-a4d3-11e6-9ad5-01e8197b691d.png)
![screen shot 2016-11-07 at 10 14 03 am](https://cloud.githubusercontent.com/assets/782228/20062800/080a8fe4-a4d3-11e6-99b7-34c6639670b8.png)

**Comment by jwzimmer** [comment]
The search bar in the navbar is cut off on the remix tree page in Catalan, but since we're eventually migrating out of scratchr2, I figured it didn't make sense to create a new issue for that, and instead am just noting it here. (It looks better on Explore, which is a www page.)

**Comment by jwzimmer** [comment]
I noticed in German that the navbar > search bar is pretty squashed even on www pages (here's the homepage):
<img width="1167" alt="screen shot 2017-02-22 at 11 59 28 am" src="https://cloud.githubusercontent.com/assets/1320456/23222867/3a9938ac-f8f7-11e6-8a5e-8f7386c2360f.png">

**Comment by rschamp** [comment]
Tracking in #1262
