### ISSUE TITLE
No error in UI (just console) for 429/ exceeding account creation rate limit

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratch-www#1124]
Blocker for https://github.com/LLK/scratch-www/pull/1110.

Staging, Mac OS El Capitan, Chrome 55

(@rschamp, please let me know if I was testing this in the wrong place or if it wasn't ready to be tested quite yet, etc. Thanks.)

**TL;DR** I get "stuck" on the last step of teacher registration if I exceed daily account creation rate limit.

I should see an error page rather than getting stuck on the second step after exceeding the registration rate limit when I register a student or teacher account. However, I get "stuck" on the last (email) step - the Next button doesn't take me off of that step. No error is displayed in the UI (there are errors in the console).

* I created regular scratch accounts using my tool to bring my IP up to daily rate limit
  * Examples: gWFGqbPLj, wNmVKGyqg
  * I registered 1, then 20, then 80
  * The IP limit per day is 100, so between those 101 and the accounts I created while testing over the day, I should be over the limit
* Then I tried registering as a new teacher
  * I got "stuck" on the last step (email)
  * The 429 error was in the console, but no error message is displayed in the UI
  * No error page

Here's what I see on clicking "Next" after registering too many accounts from one IP:
<img width="1274" alt="screen shot 2016-12-16 at 8 45 01 pm" src="https://cloud.githubusercontent.com/assets/1320456/21283479/09f44ad0-c3d1-11e6-8c19-60bf4bd15547.png">

**Comment by rschamp** [comment]
FIxed in #1128

**Comment by jwzimmer** [comment]
I am still seeing this?
Chrome 55, Mac OS El Capitan, Staging.

- I used my tool to create 101 accounts
- I registered for a teacher account
- I got stuck on the last step (email)

<img width="657" alt="screen shot 2016-12-19 at 3 33 39 pm" src="https://cloud.githubusercontent.com/assets/1320456/21328203/c691b840-c600-11e6-96a9-5fc878736170.png">

**Comment by jwzimmer** [comment]
Staging, Chrome 55, Mac OS El Capitan

Currently I'm getting stuck on the last step:
<img width="630" alt="screen shot 2016-12-19 at 4 54 45 pm" src="https://cloud.githubusercontent.com/assets/1320456/21330588/29e42b70-c60c-11e6-9a63-b9895f8898f0.png">

**Comment by jwzimmer** [comment]
I am now seeing an error page which includes the error number (429):
<img width="713" alt="screen shot 2016-12-19 at 5 17 55 pm" src="https://cloud.githubusercontent.com/assets/1320456/21331167/1b41734a-c60f-11e6-89dc-8b0697673b6a.png">

**Comment by jwzimmer** [comment]
Since I am now seeing an error page, QA-OKing the case this is a blocker for.
