### ISSUE TITLE
Incorrect Studio Project Counts

### ISSUE THREAD

**Issue by Accio1** [LLK/scratch-www#5699]
Since the new studios have released, the project count that is shown on the "Projects" tab in the studio sometimes doesn't match up with the number of the projects actually in the studio. For example, in the image below, the studio has 3 projects, but it is listed as having 4.

The opposite also sometimes happens, with a studio showing less projects in the project count than are actually in the studio. For example, in the image below, the studio has 2 projects but is listed as having 1.
![image](https://user-images.githubusercontent.com/48496940/124666921-b477e780-de7c-11eb-9ce6-56de370fbaf6.png)

### Steps to Reproduce
 
Studio with 2 projects but listed as having one: https://scratch.mit.edu/studios/5252959

### Operating System and Browser

Windows, Chrome, but I think this happens on other browsers as well because I have seen other people mentioning it.

**Comment by RedGuy12** [comment]
> Scratch shows 13 projects for scratch.mit.edu/studios/1060340, but there's only 3. It's probably counting unshared projects.

https://github.com/ScratchAddons/ScratchAddons/pull/2918#discussion_r664891714

**Comment by mxmou** [comment]
The second example is probably caused by caching - it might just take a while for the count to update after adding a project.

**Comment by leahcimto** [comment]
I think this was fixed... all of the studios that I saw this issue with now have correct project counts.

**Comment by Accio1** [comment]
> I think this was fixed... all of the studios that I saw this issue with now have correct project counts.

It's still happening for me.

**Comment by mxmou** [comment]
> I think this was fixed... all of the studios that I saw this issue with now have correct project counts.

It isn't fixed. If you're using a Scratch-related browser extension, that might be the reason why you see correct counts.
