### ISSUE TITLE
Resetting student password doesn't always reprompt

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-www#755]
If I reset the password on a student account to reprompt - it doesn’t always prompt. On safari it seemed to prompt the first time, and not on subsequent resets. On chrome I don’t think it ever re-prompted.

Steps to reproduce:
- manually create a student account (I didn't check on csv-created or join link)
- go to students view of class, click the student settings link
- click the reprompt button
- logout
- login as student in new private window with teacher username as password [on chrome I think this just logged me in fine - no prompt] [Connor reported that it logged in without prompting with Firefox 47 on ubuntu]

on safari:
- relogin as teacher in a new private window - reset student password to reprompt again
- relogin as student in a new private window - logs in without prompting

**Comment by rschamp** [comment]
At the time this was filed, I believe resetting student passwords was broken altogether, so maybe the variability was when you prompted a student who had already been prompted (before we broke prompting) vs a student who had never been prompted at all?

This should not be an issue anymore though.

**Comment by mewtaylor** [comment]
@chrisgarrity I tried this on chrome and it was fixed from the reported behavior – I think this issue is fixed now. Thoughts on closing?

**Comment by jwzimmer** [comment]
I think this is working now. I'll check it out @mewtaylor & @chrisgarrity.

**Comment by jwzimmer** [comment]
Tried to repro, could not - tried homepage & random pages in each browser (discuss, about, project page, etc.) Signed in & out at least twice in each browser to make sure I would still get taken to the password page after the initial time.

MS Edge, Chrome, Safari, Firefox, IE11

Staging, MS Edge (Win10 VM on scratch-qa machine)

- Signed in as student1class1 using teacher's name as password
- Was prompted to change password

Staging, Chrome Version 52.0.2743.82 (64-bit)

- Signed in as student1class1 using teacher's name as password
- Was prompted to change password

Staging, Safari Version 9.1.1 (11601.6.17)

- Signed in as student1class1 using teacher's name as password
- Was prompted to change password

Staging, Firefox 47.0.1

- Signed in as student1class1 using teacher's name as password
- Was prompted to change password


Staging, IE11 on Win7 VM

- Signed in as student1class1 using teacher's name as password
- Was prompted to change password
